//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFinalProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageInformation
    {
        public int packid { get; set; }
        public string sname { get; set; }
        public string saddress { get; set; }
        public string scontact { get; set; }
        public string rname { get; set; }
        public string raddress { get; set; }
        public string rcontact { get; set; }
        public int iddelmode { get; set; }
        public int iddeliver { get; set; }
    
        public virtual DeliveryMode DeliveryMode { get; set; }
        public virtual DeliveryStat DeliveryStat { get; set; }
    }
}
